// DO NOT EDIT THIS FILE!
const ProfileView = () => {
  return (
    <div>
      <h1>Profile Page</h1>
      <h3>Please consider this as a heavy view with lots of components, data and animations.</h3>
    </div>
  );
};
export default ProfileView;
