// DO NOT EDIT THIS FILE!
const StatementsView = () => {
  return (
    <div>
      <h1>Statements Page</h1>
      <h3>Please consider this as a heavy view with lots of components, data and animations.</h3>
    </div>
  );
};
export default StatementsView;
